### ISSUE TITLE
arm11 startup

### ISSUE THREAD

**Issue by V01D-NULL** [HIDE810/minifirm#1]
Hey friend, why not initialize the arm11 processor as well considering it's far more competent than it's sibling processor, the arm9?

**Comment by hide0123** [comment]
Thank you for your opinion but I have no time to work on that. If you have a good idea, I'm glad if you make a pull request (or make it as another project).

**Comment by V01D-NULL** [comment]
Sure, I'll make a PR 👍

**Comment by hide0123** [comment]
Solved #2
